### ISSUE TITLE
Captured panics from attempt at running 90 instance DHT test

### ISSUE THREAD

**Issue by jimpick** [ipfs/testground#113]
```
dht.69.t7gmaevhzjc8@ip-172-31-7-144    | panic: send on closed channel
dht.69.t7gmaevhzjc8@ip-172-31-7-144    | 
dht.69.t7gmaevhzjc8@ip-172-31-7-144    | goroutine 51 [running]:
dht.69.t7gmaevhzjc8@ip-172-31-7-144    | reflect.chansend(0xc00005b1a0, 0xc0003e3c18, 0x0, 0xb3adbf)
dht.69.t7gmaevhzjc8@ip-172-31-7-144    | 	/usr/local/go/src/runtime/chan.go:665 +0x4b
dht.88.yojucvokg4l0@ip-172-31-7-144    | panic: send on closed channel
dht.69.t7gmaevhzjc8@ip-172-31-7-144    | reflect.Value.send(0xa1d0c0, 0xc00005b1a0, 0x12, 0xa8b020, 0xc000490330, 0x16, 0x0, 0x96)
dht.69.t7gmaevhzjc8@ip-172-31-7-144    | 	/usr/local/go/src/reflect/value.go:1524 +0x118
dht.88.yojucvokg4l0@ip-172-31-7-144    | 
dht.69.t7gmaevhzjc8@ip-172-31-7-144    | reflect.Value.Send(0xa1d0c0, 0xc00005b1a0, 0x12, 0xa8b020, 0xc000490330, 0x16)
dht.88.yojucvokg4l0@ip-172-31-7-144    | goroutine 63 [running]:
dht.69.t7gmaevhzjc8@ip-172-31-7-144    | 	/usr/local/go/src/reflect/value.go:1506 +0x90
dht.88.yojucvokg4l0@ip-172-31-7-144    | reflect.chansend(0xc0003ba720, 0xc0000ebc18, 0x0, 0xb3adbf)
dht.69.t7gmaevhzjc8@ip-172-31-7-144    | github.com/ipfs/testground/sdk/sync.(*subscription).process(0xc0001a92d0)
dht.88.yojucvokg4l0@ip-172-31-7-144    | 	/usr/local/go/src/runtime/chan.go:665 +0x4b
dht.69.t7gmaevhzjc8@ip-172-31-7-144    | 	/sdk/sync/subscription.go:198 +0xf10
dht.88.yojucvokg4l0@ip-172-31-7-144    | reflect.Value.send(0xa1d0c0, 0xc0003ba720, 0x12, 0xa8b020, 0xc0002be930, 0x16, 0x0, 0x95)
dht.69.t7gmaevhzjc8@ip-172-31-7-144    | created by github.com/ipfs/testground/sdk/sync.(*subscription).start
dht.88.yojucvokg4l0@ip-172-31-7-144    | 	/usr/local/go/src/reflect/value.go:1524 +0x118
dht.88.yojucvokg4l0@ip-172-31-7-144    | reflect.Value.Send(0xa1d0c0, 0xc0003ba720, 0x12, 0xa8b020, 0xc0002be930, 0x16)
dht.88.yojucvokg4l0@ip-172-31-7-144    | 	/usr/local/go/src/reflect/value.go:1506 +0x90
dht.88.yojucvokg4l0@ip-172-31-7-144    | github.com/ipfs/testground/sdk/sync.(*subscription).process(0xc00023c9a0)
dht.69.t7gmaevhzjc8@ip-172-31-7-144    | 	/sdk/sync/subscription.go:48 +0x1ca
dht.88.yojucvokg4l0@ip-172-31-7-144    | 	/sdk/sync/subscription.go:123 +0x133c
dht.88.yojucvokg4l0@ip-172-31-7-144    | created by github.com/ipfs/testground/sdk/sync.(*subscription).start
dht.88.yojucvokg4l0@ip-172-31-7-144    | 	/sdk/sync/subscription.go:48 +0x1ca
dht.57.ru9197gw9dtw@ip-172-31-7-144    | panic: send on closed channel
dht.57.ru9197gw9dtw@ip-172-31-7-144    | 
dht.57.ru9197gw9dtw@ip-172-31-7-144    | goroutine 67 [running]:
dht.57.ru9197gw9dtw@ip-172-31-7-144    | reflect.chansend(0xc0000f8780, 0xc000475c18, 0x0, 0xb3adbf)
dht.57.ru9197gw9dtw@ip-172-31-7-144    | 	/usr/local/go/src/runtime/chan.go:665 +0x4b
dht.80.012ya7ib28em@ip-172-31-7-144    | panic: send on closed channel
dht.57.ru9197gw9dtw@ip-172-31-7-144    | reflect.Value.send(0xa1d0c0, 0xc0000f8780, 0x12, 0xa8b020, 0xc000352900, 0x16, 0x0, 0x96)
dht.80.012ya7ib28em@ip-172-31-7-144    | 
dht.57.ru9197gw9dtw@ip-172-31-7-144    | 	/usr/local/go/src/reflect/value.go:1524 +0x118
dht.80.012ya7ib28em@ip-172-31-7-144    | goroutine 68 [running]:
dht.57.ru9197gw9dtw@ip-172-31-7-144    | reflect.Value.Send(0xa1d0c0, 0xc0000f8780, 0x12, 0xa8b020, 0xc000352900, 0x16)
dht.80.012ya7ib28em@ip-172-31-7-144    | reflect.chansend(0xc0001038c0, 0xc00015fc18, 0x0, 0xb3adbf)
dht.57.ru9197gw9dtw@ip-172-31-7-144    | 	/usr/local/go/src/reflect/value.go:1506 +0x90
dht.80.012ya7ib28em@ip-172-31-7-144    | 	/usr/local/go/src/runtime/chan.go:665 +0x4b
dht.57.ru9197gw9dtw@ip-172-31-7-144    | github.com/ipfs/testground/sdk/sync.(*subscription).process(0xc000496000)
dht.80.012ya7ib28em@ip-172-31-7-144    | reflect.Value.send(0xa1d0c0, 0xc0001038c0, 0x12, 0xa8b020, 0xc000376990, 0x16, 0x0, 0x96)
dht.57.ru9197gw9dtw@ip-172-31-7-144    | 	/sdk/sync/subscription.go:123 +0x133c
dht.80.012ya7ib28em@ip-172-31-7-144    | 	/usr/local/go/src/reflect/value.go:1524 +0x118
dht.57.ru9197gw9dtw@ip-172-31-7-144    | created by github.com/ipfs/testground/sdk/sync.(*subscription).start
dht.80.012ya7ib28em@ip-172-31-7-144    | reflect.Value.Send(0xa1d0c0, 0xc0001038c0, 0x12, 0xa8b020, 0xc000376990, 0x16)
dht.80.012ya7ib28em@ip-172-31-7-144    | 	/usr/local/go/src/reflect/value.go:1506 +0x90
dht.80.012ya7ib28em@ip-172-31-7-144    | github.com/ipfs/testground/sdk/sync.(*subscription).process(0xc0000e47e0)
dht.57.ru9197gw9dtw@ip-172-31-7-144    | 	/sdk/sync/subscription.go:48 +0x1ca
dht.80.012ya7ib28em@ip-172-31-7-144    | 	/sdk/sync/subscription.go:198 +0xf10
dht.80.012ya7ib28em@ip-172-31-7-144    | created by github.com/ipfs/testground/sdk/sync.(*subscription).start
dht.80.012ya7ib28em@ip-172-31-7-144    | 	/sdk/sync/subscription.go:48 +0x1ca
dht.31.txx6bjh65256@ip-172-31-7-144    | panic: send on closed channel
dht.32.9xxmv10bzj60@ip-172-31-7-144    | {"runenv":{"test_plan":"dht","test_case":"findpeers","test_run":"jim90_1","test_seq":0,"test_instance_count":90},"timestamp":1572882179413845112,"metric":{"name":"time-to-find-0","unit":"ns","improve_dir":-1,"value":15963}}
dht.31.txx6bjh65256@ip-172-31-7-144    | 
dht.31.txx6bjh65256@ip-172-31-7-144    | goroutine 67 [running]:
dht.32.9xxmv10bzj60@ip-172-31-7-144    | {"runenv":{"test_plan":"dht","test_case":"findpeers","test_run":"jim90_1","test_seq":0,"test_instance_count":90},"timestamp":1572882179414335551,"metric":{"name":"time-to-find-1","unit":"ns","improve_dir":-1,"value":205894}}
dht.32.9xxmv10bzj60@ip-172-31-7-144    | {"runenv":{"test_plan":"dht","test_case":"findpeers","test_run":"jim90_1","test_seq":0,"test_instance_count":90},"timestamp":1572882179414392532,"metric":{"name":"time-to-find-2","unit":"ns","improve_dir":-1,"value":12042}}
dht.31.txx6bjh65256@ip-172-31-7-144    | reflect.chansend(0xc00005ad80, 0xc00004bc18, 0x0, 0xb3adbf)
dht.31.txx6bjh65256@ip-172-31-7-144    | 	/usr/local/go/src/runtime/chan.go:665 +0x4b
dht.31.txx6bjh65256@ip-172-31-7-144    | reflect.Value.send(0xa1d0c0, 0xc00005ad80, 0x12, 0xa8b020, 0xc0004e70e0, 0x16, 0x0, 0x95)
dht.32.9xxmv10bzj60@ip-172-31-7-144    | {"runenv":{"test_plan":"dht","test_case":"findpeers","test_run":"jim90_1","test_seq":0,"test_instance_count":90},"timestamp":1572882189414890210,"result":{"outcome":"aborted","msg":"context deadline exceeded"}}
dht.31.txx6bjh65256@ip-172-31-7-144    | 	/usr/local/go/src/reflect/value.go:1524 +0x118
dht.31.txx6bjh65256@ip-172-31-7-144    | reflect.Value.Send(0xa1d0c0, 0xc00005ad80, 0x12, 0xa8b020, 0xc0004e70e0, 0x16)
dht.31.txx6bjh65256@ip-172-31-7-144    | 	/usr/local/go/src/reflect/value.go:1506 +0x90
dht.31.txx6bjh65256@ip-172-31-7-144    | github.com/ipfs/testground/sdk/sync.(*subscription).process(0xc0000e42a0)
dht.31.txx6bjh65256@ip-172-31-7-144    | 	/sdk/sync/subscription.go:123 +0x133c
dht.31.txx6bjh65256@ip-172-31-7-144    | created by github.com/ipfs/testground/sdk/sync.(*subscription).start
dht.31.txx6bjh65256@ip-172-31-7-144    | 	/sdk/sync/subscription.go:48 +0x1ca
```

**Comment by raulk** [comment]
Looks like the timeout for the DHT test is too low for that amount of instances. Try increasing the timeout when running the test plan:

```
./testground [...] --test-param timeout_secs=300
```

**Comment by raulk** [comment]
Fixed in https://github.com/ipfs/testground/pull/117.
