### ISSUE TITLE
panic when running testground testplan with docker

### ISSUE THREAD

**Issue by dirkmc** [ipfs/testground#334]
When running any testplan with docker, I get a panic in sidecar.

`$ ./testground run network/ping-pong     --builder=docker:go     --runner=local:docker`

Daemon output:
```
found cached docker image for: testground-network:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Jan 13 15:11:20.971994	INFO	container isn't running; starting	{"runner": "local:docker", "run_id": "0c062a3f-fa3f-4ab6-af5f-6d2d28edf8f9", "containerName": "testground-sidecar"}
Jan 13 15:11:21.595915	INFO	creating container	{"runner": "local:docker", "run_id": "0c062a3f-fa3f-4ab6-af5f-6d2d28edf8f9", "name": "tg-network-ping-pong-0c062a3f-fa3f-4ab6-af5f-6d2d28edf8f9-0"}
Jan 13 15:11:21.727678	INFO	creating container	{"runner": "local:docker", "run_id": "0c062a3f-fa3f-4ab6-af5f-6d2d28edf8f9", "name": "tg-network-ping-pong-0c062a3f-fa3f-4ab6-af5f-6d2d28edf8f9-1"}
Jan 13 15:11:21.838411	INFO	starting containers	{"runner": "local:docker", "run_id": "0c062a3f-fa3f-4ab6-af5f-6d2d28edf8f9", "count": 2}
Jan 13 15:11:22.993328	INFO	started containers	{"runner": "local:docker", "run_id": "0c062a3f-fa3f-4ab6-af5f-6d2d28edf8f9", "count": 2}
  29.7916s       FAIL << 838460cd9d98 >> aborted context deadline exceeded waiting on network-configured; not enough elements, required: 2, got: 0
  29.9702s       FAIL << 1920e1fff9be >> aborted context deadline exceeded waiting on network-configured; not enough elements, required: 2, got: 0
Jan 13 15:11:53.087401	INFO	deleting containers	{"runner": "local:docker", "run_id": "0c062a3f-fa3f-4ab6-af5f-6d2d28edf8f9", "ids": ["838460cd9d98b9d47b152f57a683883a8f9258a3f548f8a00f61106a8cad80a7", "1920e1fff9be09a27cd069aa366fe7fced7fef4a4c46bd445901069bd6a6368e"]}
Jan 13 15:11:54.057789	WARN	engine run error	{"ruid": "a0b9662b", "err": "2 nodes failed"}
```

Sidecar logs:
```
2020-01-13T15:11:23.107045000Z panic: WRONGTYPE Operation against a key holding the wrong kind of value
2020-01-13T15:11:23.107094600Z 
2020-01-13T15:11:23.107126000Z goroutine 86 [running]:
2020-01-13T15:11:23.107155900Z github.com/ipfs/testground/sdk/sync.(*subscription).process(0xc0002886c0)
2020-01-13T15:11:23.107185100Z 	/sdk/sync/subscription.go:96 +0x1655
2020-01-13T15:11:23.107220500Z github.com/ipfs/testground/sdk/sync.(*subscription).start.func1(0xc0002886c0)
2020-01-13T15:11:23.107248100Z 	/sdk/sync/subscription.go:52 +0x2b
2020-01-13T15:11:23.107279800Z created by github.com/ipfs/testground/sdk/sync.(*subscription).start
2020-01-13T15:11:23.107317900Z 	/sdk/sync/subscription.go:51 +0x1e5
```

This seems to be caused by [performing a Redis operation against a key type that doesn't support that operation](https://stackoverflow.com/questions/37953019/wrongtype-operation-against-a-key-holding-the-wrong-kind-of-value-php).

**Comment by dirkmc** [comment]
Solution was to run `docker system prune -a` to clear out old docker containers (specifically I think I needed to get rid of the redis container)
